server:
    port: 3000

pokerwars:
    bot:
        username: shankey
        token: iEMShPnbjVWYwPtBAMSPCxFV9EVPr9Kn
        # make sure your bot can be seen from external at the IP and port you specify below, so pokerwars.io can talk to him/her.
        # this is an useful service to double check this: http://canyouseeme.org/ . Bot default port is `3000`, but you can change this just above in this file
        endpoint:
        # options are ALWAYS_FOLD, ALWAYS_CALL or RANDOM, implement your own strategy!
        # to activate the parametrised bot, use type CARD_BASED
        strategy:
            type: CARD_BASED
            aggressiveness: 3
            bluff: 1
            raise-factor: 2
        # pokerwars can send you notifications to know how your bot is doing
        notifications: true
    server: https://play.pokerwars.io

logging:
    file: logs/pokerwars.io-starterbot-java.log
    level:
        io.pokerwars: info        

spring:
    jackson:
        mapper:
            ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: false
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/poker
        username: root
        password:
#        autoconfigure:
#                exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    jpa:
        hibernate:
#            ddlAuto: update
            databasePlatform: org.hibernate.dialect.MySQL5Dialect
#            generateDdl: true
